image: "dothanhtrung/bevy-dev:latest"

check:
  stage: build
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check --example basic
    - cargo check --example no_state
    - cargo check --example get_text
  cache:
    key: check-cache
    paths:
      - ../target/

publish:
  stage: deploy
  script:
    - cargo publish --token $TOKEN
  cache:
    key: check-cache
    paths:
      - ../target/
  only:
    - tags